swagger: "2.0"
info:
  title: "Car Shop API"
  description: "This is an API for a car shop application that allows users to manage service tickets, customers, and inventory."
  version: "1.0.0"
host: "127.0.0.1:5000"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"

securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header

paths:
  /members/login:
    post:
      tags:
        - members
      summary: "Login endpoint, (generates token)"
      description: "Validates member credentials, generates and return a member specific token."
      parameters:
        - in: "body"
          name: "body"
          description: "Login Credentials"
          required: true
          schema:
            $ref: "#/definitions/LoginCredentials"
      responses:
        200:
          description: "Login successful"
          schema:
            $ref: "#/definitions/LoginResponse"
  /members: #endpoint
    post: #Post request
      tags:
        - Members
      summary: "Endpoint to create/register a new user."
      description: "Endpoint to create a new member in our Library system, emails must be unique."
      parameters:
        - in: "body"
          name: "body"
          description: "Information required to create a new Member."
          required: true
          schema:
            $ref: "#/definitions/CreateMemberPayload"
      responses:
        201:
          description: "Successful Member Creation"
          schema:
            $ref: "#/definitions/CreateMemberResponse"
          examples:
            application/json:
              id: 1
              name: John Doe
              DOB: "1900-01-01"
              email: johnd@email.com
              password: password123
    get:
      tags:
        - Members
      summary: "Returns all Members"
      description: "Endpoint to retrieve a list of all members."
      responses:
        200:
          description: "Retrieved Members Successfully"
          schema:
            $ref: "#/definitions/AllMembers"
    put:
      tags:
        - Members
      summary: "Endpoint to update a user."
      description: "Endpoint to update a member, this is a token authenticated route, and the user must be logged in to update their account."
      security:
        - bearerAuth: []
      parameters:
        - in: "body"
          name: "body"
          description: "Information required to update a Member."
          required: true
          schema:
            $ref: "#/definitions/UpdateMemberPayload"
      responses:
        200:
          description: "Successfully Updated member"
          schema:
            $ref: "#/definitions/UpdateMemberResponse"
          examples:
            application/json:
              id: 1
              name: Dohn Joe
              DOB: "1900-01-01"
              email: dohnj@email.com
              password: password123
    delete:
      tags:
        - Members
      summary: "Enpoint to delete a member"
      description: "Endpoint to delete a member. Requires token authentication, member must be logged in to delete their account"
      security:
        - bearerAuth: []
      responses:
        200:
          description: "Successfully Deleted member"
          schema:
            $ref: "#/definitions/DeleteMemberResponse"
          examples:
            application/json:
              message: "successfully deleted user <member_id>."
  /mechanics:
    get:
      tags:
        - Mechanics
      summary: "Returns all Mechanics"
      description: "Endpoint to retrieve a list of all mechanics."
      responses:
        200:
          description: "Retrieved Mechanics Successfully"
          schema:
            $ref: "#/definitions/AllMechanics"
    post:
      tags:
        - Mechanics
      summary: "Endpoint to create/register a new mechanic."
      description: "Endpoint to create a new mechanic in our system, emails must be unique."
      parameters:
        - in: "body"
          name: "body"
          description: "Information required to create a new Mechanic."
          required: true
          schema:
            $ref: "#/definitions/CreateMechanicPayload"
      responses:
        201:
          description: "Successful Mechanic Creation"
          schema:
            $ref: "#/definitions/CreateMechanicResponse"
          examples:
            application/json:
              id: 1
              name: John Doe
              DOB: "1900-01-01"
              email: johnd@email.com
              password: password123
    delete:
      tags:
        - Mechanics
      summary: "Enpoint to delete a mechanic"
      description: "Endpoint to delete a mechanic. Requires token authentication, member must be logged in to delete their account"
      security:
        - bearerAuth: []
      responses:
        200:
          description: "Successfully Deleted mechanic"
          schema:
            $ref: "#/definitions/DeleteMechanicResponse"
          examples:
            application/json:
              message: "successfully deleted user <mechanic_id>."
    put:
      tags:
        - Mechanics
      summary: "Endpoint to update a mechanic."
      description: "Endpoint to update a mechanic, this is a token authenticated route, and the user must be logged in to update their account."
      security:
        - bearerAuth: []
      parameters:
        - in: "body"
          name: "body"
          description: "Information required to update a Mechanic."
          required: true
          schema:
            $ref: "#/definitions/UpdateMechanicPayload"
      responses:
        200:
          description: "Successfully Updated mechanic"
          schema:
            $ref: "#/definitions/UpdateMechanicResponse"
          examples:
            application/json:
              id: 1
              name: Dohn Joe
              DOB: "1900-01-01"
              email: dohnj@email.com
              password: password123
  /service-tickets:
    get:
      tags:
        - Service Tickets
      summary: "Returns all Service Tickets"
      description: "Endpoint to retrieve a list of all service tickets."
      responses:
        200:
          description: "Retrieved Service Tickets Successfully"
          schema:
            $ref: "#/definitions/AllServiceTickets"
    post:
      tags:
        - Service Tickets
      summary: "Endpoint to create a new service ticket."
      description: "Endpoint to create a new service ticket in our system."
      parameters:
        - in: "body"
          name: "body"
          description: "Information required to create a new Service Ticket."
          required: true
          schema:
            $ref: "#/definitions/CreateServiceTicketPayload"
      responses:
        201:
          description: "Successful Service Ticket Creation"
          schema:
            $ref: "#/definitions/CreateServiceTicketResponse"

  /service-tickets/{ticket_id}:
    put:
      tags:
        - Service Tickets
      summary: "Endpoint to update a service ticket."
      description: "Endpoint to update a service ticket."
      parameters:
        - in: "path"
          name: "ticket_id"
          required: true
          type: "integer"
        - in: "body"
          name: "body"
          description: "Information required to update a Service Ticket."
          required: true
          schema:
            $ref: "#/definitions/UpdateServiceTicketPayload"
      responses:
        200:
          description: "Successfully Updated service ticket"
          schema:
            $ref: "#/definitions/UpdateServiceTicketResponse"

  /service-tickets/{ticket_id}/assign-mechanic/{mechanic_id}:
    put:
      tags:
        - Service Tickets
      summary: "Endpoint to assign a mechanic to a service ticket."
      description: "Endpoint to assign a mechanic to a service ticket."
      parameters:
        - in: "path"
          name: "ticket_id"
          required: true
          type: "integer"
        - in: "path"
          name: "mechanic_id"
          required: true
          type: "integer"
      responses:
        200:
          description: "Successfully Assigned mechanic to service ticket"
          schema:
            $ref: "#/definitions/AssignMechanicResponse"

  /service-tickets/{ticket_id}/remove-mechanic/{mechanic_id}:
    put:
      tags:
        - Service Tickets
      summary: "Endpoint to remove a mechanic from a service ticket."
      description: "Endpoint to remove a mechanic from a service ticket."
      parameters:
        - in: "path"
          name: "ticket_id"
          required: true
          type: "integer"
        - in: "path"
          name: "mechanic_id"
          required: true
          type: "integer"
      responses:
        200:
          description: "Successfully Removed mechanic from service ticket"
          schema:
            $ref: "#/definitions/RemoveMechanicResponse"

  /service-tickets/{ticket_id}/edit:
    put:
      tags:
        - Service Tickets
      summary: "Endpoint to bulk add/remove mechanics from a service ticket."
      description: "Endpoint to edit the mechanics assigned to a service ticket by providing lists of IDs to add and remove."
      parameters:
        - in: "path"
          name: "ticket_id"
          required: true
          type: "integer"
        - in: "body"
          name: "body"
          description: "Lists of mechanic IDs to add and remove."
          required: true
          schema:
            $ref: "#/definitions/EditMechanicPayload"
      responses:
        200:
          description: "Successfully Edited mechanics on service ticket"
          schema:
            $ref: "#/definitions/EditMechanicResponse"

definitions:
  LoginCredentials:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"

    required:
      - email
      - password

  LoginResponse:
    type: "object"
    properties:
      token:
        type: "string"
      message:
        type: "string"
      status:
        type: "string"

  CreateMemberPayload:
    type: "object"
    properties:
      name:
        type: "string"
      email:
        type: "string"
      DOB:
        type: "string"
        format: date
      password:
        type: "string"

    required:
      - name
      - email
      - DOB
      - password

  CreateMemberResponse:
    type: "object"
    properties:
      id:
        type: "int"
      name:
        type: "string"
      email:
        type: "string"
      DOB:
        type: "string"
        format: date
      password:
        type: "string"

  AllMembers:
    type: "array"
    items:
      type: "object"
      properties:
        id:
          type: "integer"
        name:
          type: "string"
        email:
          type: "string"
        DOB:
          type: "string"
          format: date
        password:
          type: "string"

  UpdateMemberPayload:
    type: "object"
    properties:
      name:
        type: "string"
      email:
        type: "string"
      DOB:
        type: "string"
        format: "date"
      password:
        type: "string"

    required:
      - name
      - email
      - DOB
      - password

  UpdateMemberResponse:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      email:
        type: "string"
      DOB:
        type: "string"
      password:
        type: "string"

  DeleteMemberResponse:
    type: "object"
    properties:
      message:
        type: "string"

  DeleteServiceTicketResponse:
    type: "object"
    properties:
      message:
        type: "string"
